// ── ANNEXE AI — Workflow Database Schema ─────────────────────────────────────
//
// Future PostgreSQL schema for the ANNEXE workflow engine.
// Phase 4: pass WORKFLOW_SCHEMA to a database adapter to auto-migrate.
//
// Convention:
//   - All IDs are UUIDs generated by the database (DEFAULT gen_random_uuid())
//   - All timestamps are UTC (TIMESTAMPTZ)
//   - Foreign keys are enforced at the database level
//   - status columns use CHECK constraints matching application enums
//
// ─────────────────────────────────────────────────────────────────────────────

export const WORKFLOW_SCHEMA = {

  // ── workflows ───────────────────────────────────────────────────────────────
  //
  // One row per project workflow instance.

  workflows: {

    table: "workflows",

    columns: {

      id: {
        type:       "UUID",
        primary:    true,
        default:    "gen_random_uuid()",
        nullable:   false
      },

      project_id: {
        type:       "VARCHAR(64)",
        nullable:   false,
        index:      true,
        comment:    "References the ANNEXE project ID (e.g. ANNEXE-1234567890)"
      },

      name: {
        type:       "VARCHAR(255)",
        nullable:   false,
        default:    "'ANNEXE Workflow'"
      },

      status: {
        type:       "VARCHAR(20)",
        nullable:   false,
        default:    "'CREATED'",
        check:      "status IN ('CREATED','PLANNING','RUNNING','COMPLETED','FAILED')"
      },

      created_at: {
        type:       "TIMESTAMPTZ",
        nullable:   false,
        default:    "NOW()"
      },

      updated_at: {
        type:       "TIMESTAMPTZ",
        nullable:   false,
        default:    "NOW()"
      }

    }

  },


  // ── workflow_tasks ──────────────────────────────────────────────────────────
  //
  // One row per task within a workflow.
  // `depends_on` references another workflow_tasks.task_id (nullable = no deps).

  workflow_tasks: {

    table: "workflow_tasks",

    columns: {

      id: {
        type:       "UUID",
        primary:    true,
        default:    "gen_random_uuid()",
        nullable:   false
      },

      workflow_id: {
        type:       "UUID",
        nullable:   false,
        references: "workflows(id) ON DELETE CASCADE",
        index:      true
      },

      task_id: {
        type:       "VARCHAR(128)",
        nullable:   false,
        comment:    "Application-level task identifier (e.g. TASK-001-ARCHITECT-AGENT)"
      },

      depends_on: {
        type:       "VARCHAR(128)",
        nullable:   true,
        comment:    "task_id of the prerequisite task; NULL means no dependency"
      },

      status: {
        type:       "VARCHAR(20)",
        nullable:   false,
        default:    "'pending'",
        check:      "status IN ('pending','running','completed','failed','skipped')"
      },

      created_at: {
        type:       "TIMESTAMPTZ",
        nullable:   false,
        default:    "NOW()"
      }

    }

  },


  // ── workflow_runs ───────────────────────────────────────────────────────────
  //
  // Execution log — one row per workflow execution attempt.
  // Allows the same workflow to be re-run after failure.

  workflow_runs: {

    table: "workflow_runs",

    columns: {

      id: {
        type:       "UUID",
        primary:    true,
        default:    "gen_random_uuid()",
        nullable:   false
      },

      project_id: {
        type:       "VARCHAR(64)",
        nullable:   false,
        index:      true
      },

      workflow_id: {
        type:       "UUID",
        nullable:   false,
        references: "workflows(id) ON DELETE CASCADE",
        index:      true
      },

      status: {
        type:       "VARCHAR(20)",
        nullable:   false,
        default:    "'pending'",
        check:      "status IN ('pending','running','completed','failed')"
      },

      started_at: {
        type:       "TIMESTAMPTZ",
        nullable:   true,
        comment:    "Set when the run transitions to running"
      },

      completed_at: {
        type:       "TIMESTAMPTZ",
        nullable:   true,
        comment:    "Set when the run reaches a terminal state (completed or failed)"
      }

    }

  }

};


export default WORKFLOW_SCHEMA;
