const PROTECTED_BRANCHES = new Set(["main", "master", "production", "release"]);
const BRANCH_PREFIX = "annexe-ai";

function slugify(text = "") {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 50);
}

function generateWorkingBranch(taskName = "") {
  const slug = slugify(taskName) || "feature-update";
  return `${BRANCH_PREFIX}/feature-${slug}`;
}

function validateBaseBranch(baseBranch = "") {
  return (baseBranch || "main").trim().toLowerCase() || "main";
}

function generateCommitInfo(taskName, projectId) {
  return {
    message:     `feat(annexe-ai): ${taskName}`,
    description: `Automated engineering task initiated by ANNEXE AI for project ${projectId || "unknown"}`,
    author:      "ANNEXE AI Engineering Agent",
    status:      "pending",
    files:       []
  };
}

function generatePullRequest(taskName, workingBranch, baseBranch, projectId) {
  return {
    title: `[ANNEXE AI] ${taskName}`,
    description: [
      `## Summary`,
      `Automated pull request generated by ANNEXE AI Engineering Agent.`,
      ``,
      `**Project ID:** ${projectId || "N/A"}`,
      `**Task:** ${taskName}`,
      `**Source branch:** \`${workingBranch}\``,
      `**Target branch:** \`${baseBranch}\``,
      ``,
      `## Review checklist`,
      `- [ ] Code reviewed by human engineer`,
      `- [ ] Tests passing`,
      `- [ ] No secrets or credentials in diff`,
      `- [ ] Approved for merge`
    ].join("\n"),
    sourceBranch:   workingBranch,
    targetBranch:   baseBranch,
    reviewRequired: true,
    mergeAllowed:   false,
    status:         "draft"
  };
}

export function runRepositoryManagerAgent({
  repositoryUrl = null,
  projectId     = null,
  taskName      = "feature-update",
  baseBranch    = "main"
} = {}) {

  const resolvedBase  = validateBaseBranch(baseBranch);
  const workingBranch = generateWorkingBranch(taskName);

  if (PROTECTED_BRANCHES.has(workingBranch)) {
    return {
      success: false,
      agent:   "repository_manager_agent",
      version: "1.0.0",
      error:   `Generated branch '${workingBranch}' conflicts with a protected branch. Aborting.`,
      repositoryState: null
    };
  }

  const repositoryState = {
    repositoryUrl,
    baseBranch:  resolvedBase,
    workingBranch,
    status:      "prepared",
    changes:     [],
    commits:     [generateCommitInfo(taskName, projectId)],
    pullRequest: generatePullRequest(taskName, workingBranch, resolvedBase, projectId)
  };

  return {
    success: true,
    agent:   "repository_manager_agent",
    version: "1.0.0",
    repositoryState,
    _meta: {
      projectId,
      repositoryUrl,
      baseBranch:                 resolvedBase,
      workingBranch,
      protectedBranchesRespected: !PROTECTED_BRANCHES.has(workingBranch),
      generatedAt:                new Date().toISOString()
    }
  };
}

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });
  try {
    const { repositoryUrl, projectId, taskName, baseBranch } = req.body || {};
    if (!repositoryUrl) return res.status(400).json({ error: "repositoryUrl is required" });
    return res.status(200).json(runRepositoryManagerAgent({ repositoryUrl, projectId, taskName, baseBranch }));
  } catch (error) {
    console.error("REPOSITORY MANAGER AGENT ERROR:", error);
    return res.status(500).json({ error: "Repository manager failed" });
  }
}