// ───────────────────────────────────────────────────────────────
// ANNEXE AI V9
// Phase 12.2
// Project Writer
// BuildManifest → Workspace
// ───────────────────────────────────────────────────────────────

import fs from "fs";
import path from "path";

import WriteReport from "./contracts/write-report.js";

function normalizePath(filePath = "") {
    return String(filePath).replace(/\\/g, "/");
}

function makeFile(filePath, content, options = {}) {
    return {
        path: normalizePath(filePath),
        content,
        type: options.type ?? "source",
        language: options.language ?? "text",
        encoding: options.encoding ?? "utf8",
        overwrite: options.overwrite ?? true,
        executable: options.executable ?? false
    };
}

function block(text) {
    return text.trimStart();
}

export default class ProjectWriter {

    constructor(options = {}) {
        this.workspaceRoot = options.workspaceRoot ?? "workspace";
    }

    buildRootFiles({ projectName, blueprint }) {
        return [
            makeFile(
                "README.md",
                block(`
# ${projectName}

Generated by ANNEXE AI.

## Stack

- Backend: ${blueprint.metadata?.stack?.backend ?? blueprint.architecture?.backend ?? "FastAPI"}
- Frontend: ${blueprint.metadata?.stack?.frontend ?? blueprint.architecture?.frontend ?? "React + Vite"}
- Database: ${blueprint.metadata?.stack?.database ?? blueprint.architecture?.database ?? "PostgreSQL"}
`),
                { type: "documentation", language: "markdown" }
            ),
            makeFile(
                "enterprise-crm.blueprint.json",
                JSON.stringify(blueprint, null, 2) + "\n",
                { type: "artifact", language: "json" }
            )
        ];
    }

    buildBackendTemplate({ projectName, modules, entities, services, apis }) {
        const moduleList = modules.length ? modules : ["Authentication", "Dashboard", "Customers", "Reporting"];
        const entityList = entities.length ? entities : ["User", "Customer", "Activity"];
        const serviceList = services.length ? services : ["Authentication Service", "Customer Service"];
        const apiList = apis.length ? apis : ["/auth/login", "/auth/me", "/customers", "/crm/summary"];
        const defaultAdminEmail = "admin@annexe.ai";
        const defaultAdminPassword = "Admin123!";
        const seedCustomers = [
            {
                name: "Apex Retail Group",
                email: "hello@apexretail.com",
                company: "Apex Retail Group",
                status: "active",
                phone: "+1-202-555-0142",
                owner: "Enterprise Sales",
                notes: "High priority enterprise account."
            },
            {
                name: "Northwind Logistics",
                email: "ops@northwindlogistics.com",
                company: "Northwind Logistics",
                status: "active",
                phone: "+1-202-555-0168",
                owner: "Customer Success",
                notes: "Expansion candidate for Q3."
            },
            {
                name: "BluePeak Health",
                email: "care@bluepeakhealth.com",
                company: "BluePeak Health",
                status: "prospect",
                phone: "+1-202-555-0191",
                owner: "Sales Operations",
                notes: "Awaiting security review."
            }
        ];

        return [
            makeFile("backend/requirements.txt", [
                "fastapi>=0.115.0",
                "uvicorn[standard]>=0.30.0",
                "sqlalchemy>=2.0.0",
                "python-dotenv>=1.0.1"
            ].join("\n") + "\n", { type: "configuration", language: "text" }),
            makeFile("backend/Dockerfile", block(`
FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
`), { type: "configuration", language: "dockerfile" }),
            makeFile("backend/.env.example", [
                `APP_NAME=${projectName}`,
                "APP_ENV=development",
                "DATABASE_URL=sqlite:///./crm.db",
                "SECRET_KEY=change-me-in-production",
                "ACCESS_TOKEN_EXPIRE_MINUTES=480",
                `ADMIN_EMAIL=${defaultAdminEmail}`,
                `ADMIN_PASSWORD=${defaultAdminPassword}`,
                "CORS_ORIGINS=http://localhost:5173"
            ].join("\n") + "\n", { type: "configuration", language: "env" }),
            makeFile("backend/README.md", block(`
# ${projectName} Backend

## Features

- FastAPI application with OpenAPI documentation
- JWT authentication
- SQLAlchemy persistence
- Customer CRUD endpoints
- Seeded admin user and sample customers

## Default Login

- Email: ${defaultAdminEmail}
- Password: ${defaultAdminPassword}

## Run

1. Create a virtual environment.
2. Install dependencies from \`requirements.txt\`.
3. Start the app with \`python -m uvicorn app.main:app\`.
`), { type: "documentation", language: "markdown" }),
            makeFile("backend/app/__init__.py", "", { type: "source", language: "python" }),
            makeFile("backend/app/config.py", block(`
import os


class Settings:
    app_name = os.getenv("APP_NAME", "${projectName}")
    app_env = os.getenv("APP_ENV", "development")
    database_url = os.getenv("DATABASE_URL", "sqlite:///./crm.db")
    secret_key = os.getenv("SECRET_KEY", "change-me-in-production")
    access_token_expire_minutes = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "480"))
    admin_email = os.getenv("ADMIN_EMAIL", "${defaultAdminEmail}")
    admin_password = os.getenv("ADMIN_PASSWORD", "${defaultAdminPassword}")
    cors_origins = [
        origin.strip()
        for origin in os.getenv("CORS_ORIGINS", "http://localhost:5173").split(",")
        if origin.strip()
    ]


settings = Settings()
`), { type: "source", language: "python" }),
            makeFile("backend/app/database.py", block(`
from contextlib import contextmanager

from sqlalchemy import create_engine
from sqlalchemy.pool import StaticPool
from sqlalchemy.orm import declarative_base, sessionmaker

from .config import settings


Base = declarative_base()

if settings.database_url.startswith("sqlite"):
    engine = create_engine(
        "sqlite:///:memory:",
        future=True,
        echo=False,
        connect_args={"check_same_thread": False},
        poolclass=StaticPool
    )
else:
    engine = create_engine(settings.database_url, future=True, echo=False)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine, future=True)


def init_db():
    from .models import crm  # noqa: F401

    Base.metadata.create_all(bind=engine)


@contextmanager
def session_scope():
    session = SessionLocal()
    try:
        yield session
    finally:
        session.close()


def get_db():
    with session_scope() as db:
        yield db
`), { type: "source", language: "python" }),
            makeFile("backend/app/security.py", block(`
import base64
import hashlib
import hmac
import json
import secrets
import time

from fastapi import HTTPException, status


def _b64encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode("utf-8").rstrip("=")


def _b64decode(data: str) -> bytes:
    padding = "=" * (-len(data) % 4)
    return base64.urlsafe_b64decode(data + padding)


def hash_password(password: str, salt: str | None = None) -> str:
    salt_value = salt or secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt_value.encode("utf-8"),
        120000
    ).hex()
    return f"pbkdf2_sha256\${salt_value}\${digest}"


def verify_password(password: str, hashed_password: str) -> bool:
    try:
        _, salt_value, digest = hashed_password.split("$", 2)
    except ValueError:
        return False

    candidate = hash_password(password, salt_value)
    return hmac.compare_digest(candidate, hashed_password)


def create_access_token(subject: str, secret_key: str, expires_minutes: int, extra_claims: dict | None = None) -> str:
    header = {"alg": "HS256", "typ": "JWT"}
    issued_at = int(time.time())
    payload = {
        "sub": subject,
        "iat": issued_at,
        "exp": issued_at + (expires_minutes * 60)
    }
    if extra_claims:
        payload.update(extra_claims)

    signing_input = f"{_b64encode(json.dumps(header, separators=(',', ':')).encode('utf-8'))}.{_b64encode(json.dumps(payload, separators=(',', ':')).encode('utf-8'))}"
    signature = hmac.new(secret_key.encode("utf-8"), signing_input.encode("utf-8"), hashlib.sha256).digest()
    return f"{signing_input}.{_b64encode(signature)}"


def decode_access_token(token: str, secret_key: str) -> dict:
    try:
        header_part, payload_part, signature_part = token.split(".")
        signing_input = f"{header_part}.{payload_part}"
        expected_signature = _b64encode(
            hmac.new(secret_key.encode("utf-8"), signing_input.encode("utf-8"), hashlib.sha256).digest()
        )
        if not hmac.compare_digest(expected_signature, signature_part):
            raise ValueError("Invalid signature")

        payload = json.loads(_b64decode(payload_part))
        if int(payload.get("exp", 0)) < int(time.time()):
            raise ValueError("Token expired")
        return payload
    except Exception as exc:  # pragma: no cover - defensive auth guard
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired token"
        ) from exc
`), { type: "source", language: "python" }),
            makeFile("backend/app/models/__init__.py", block(`
from .crm import Base, Customer, User
`), { type: "source", language: "python" }),
            makeFile("backend/app/models/crm.py", block(`
from datetime import datetime

from sqlalchemy import Boolean, Column, DateTime, Integer, String, Text

from ..database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), unique=True, index=True, nullable=False)
    full_name = Column(String(255), nullable=False)
    hashed_password = Column(String(255), nullable=False)
    role = Column(String(64), nullable=False, default="Administrator")
    is_active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)


class Customer(Base):
    __tablename__ = "customers"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False)
    email = Column(String(255), unique=True, nullable=True)
    company = Column(String(255), nullable=True)
    status = Column(String(64), nullable=False, default="active")
    phone = Column(String(64), nullable=True)
    owner = Column(String(255), nullable=True)
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
`), { type: "source", language: "python" }),
            makeFile("backend/app/schemas/__init__.py", block(`
from .crm import CustomerCreate, CustomerRead, CustomerUpdate, DashboardSummary, LoginRequest, LoginResponse, UserRead
`), { type: "source", language: "python" }),
            makeFile("backend/app/schemas/crm.py", block(`
from datetime import datetime

from pydantic import BaseModel, ConfigDict


class UserRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    email: str
    full_name: str
    role: str
    is_active: bool
    created_at: datetime


class LoginRequest(BaseModel):
    email: str
    password: str


class LoginResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user: UserRead


class CustomerBase(BaseModel):
    name: str
    email: str | None = None
    company: str | None = None
    phone: str | None = None
    status: str = "active"
    owner: str | None = None
    notes: str | None = None


class CustomerCreate(CustomerBase):
    pass


class CustomerUpdate(BaseModel):
    name: str | None = None
    email: str | None = None
    company: str | None = None
    phone: str | None = None
    status: str | None = None
    owner: str | None = None
    notes: str | None = None


class CustomerRead(CustomerBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    created_at: datetime
    updated_at: datetime


class DashboardSummary(BaseModel):
    project: str
    modules: list[str]
    customer_count: int
    active_customer_count: int
    user_count: int
    recent_customers: list[CustomerRead]
`), { type: "source", language: "python" }),
            makeFile("backend/app/repositories/__init__.py", block(`
from .crm_repository import CRMRepository
`), { type: "source", language: "python" }),
            makeFile("backend/app/repositories/crm_repository.py", block(`
from sqlalchemy import func, select

from ..models import Customer, User
from ..security import hash_password


class CRMRepository:
    @staticmethod
    def get_user_by_email(db, email: str):
        normalized_email = (email or "").strip().lower()
        if not normalized_email:
            return None
        return db.scalars(select(User).where(User.email == normalized_email)).first()

    @staticmethod
    def get_customer(db, customer_id: int):
        return db.get(Customer, customer_id)

    @staticmethod
    def list_customers(db):
        return db.scalars(select(Customer).order_by(Customer.created_at.desc(), Customer.id.desc())).all()

    @staticmethod
    def create_customer(db, payload):
        customer = Customer(**payload)
        db.add(customer)
        db.commit()
        db.refresh(customer)
        return customer

    @staticmethod
    def update_customer(db, customer: Customer, payload):
        for key, value in payload.items():
            if value is not None:
                setattr(customer, key, value)
        db.add(customer)
        db.commit()
        db.refresh(customer)
        return customer

    @staticmethod
    def delete_customer(db, customer: Customer):
        db.delete(customer)
        db.commit()

    @staticmethod
    def dashboard_summary(db, project_name: str, modules: list[str]):
        customer_count = db.scalar(select(func.count()).select_from(Customer)) or 0
        user_count = db.scalar(select(func.count()).select_from(User)) or 0
        active_customer_count = db.scalar(
            select(func.count()).select_from(Customer).where(Customer.status == "active")
        ) or 0
        recent_customers = db.scalars(
            select(Customer).order_by(Customer.created_at.desc(), Customer.id.desc()).limit(5)
        ).all()
        return {
            "project": project_name,
            "modules": modules,
            "customer_count": customer_count,
            "active_customer_count": active_customer_count,
            "user_count": user_count,
            "recent_customers": recent_customers
        }

    @staticmethod
    def ensure_seed_data(db, admin_email: str, admin_password: str, project_name: str):
        user = CRMRepository.get_user_by_email(db, admin_email)
        if user is None:
            db.add(
                User(
                    email=admin_email.lower(),
                    full_name=f"{project_name} Admin",
                    hashed_password=hash_password(admin_password),
                    role="Administrator",
                    is_active=True
                )
            )

        customer_count = db.scalar(select(func.count()).select_from(Customer)) or 0
        if customer_count == 0:
            samples = [
                {
                    "name": "Apex Retail Group",
                    "email": "hello@apexretail.com",
                    "company": "Apex Retail Group",
                    "status": "active",
                    "phone": "+1-202-555-0142",
                    "owner": "Enterprise Sales",
                    "notes": "High priority enterprise account."
                },
                {
                    "name": "Northwind Logistics",
                    "email": "ops@northwindlogistics.com",
                    "company": "Northwind Logistics",
                    "status": "active",
                    "phone": "+1-202-555-0168",
                    "owner": "Customer Success",
                    "notes": "Expansion candidate for Q3."
                },
                {
                    "name": "BluePeak Health",
                    "email": "care@bluepeakhealth.com",
                    "company": "BluePeak Health",
                    "status": "prospect",
                    "phone": "+1-202-555-0191",
                    "owner": "Sales Operations",
                    "notes": "Awaiting security review."
                }
            ]
            for customer in samples:
                db.add(Customer(**customer))

        db.commit()
`), { type: "source", language: "python" }),
            makeFile("backend/app/services/__init__.py", block(`
from .crm_service import CRMService
`), { type: "source", language: "python" }),
            makeFile("backend/app/services/crm_service.py", block(`
from fastapi import HTTPException, status

from ..config import settings
from ..repositories.crm_repository import CRMRepository
from ..security import create_access_token, verify_password


class CRMService:
    def __init__(self):
        self.project_name = settings.app_name
        self.modules = ${JSON.stringify(moduleList, null, 2)}
        self.entities = ${JSON.stringify(entityList, null, 2)}
        self.services = ${JSON.stringify(serviceList, null, 2)}
        self.apis = ${JSON.stringify(apiList, null, 2)}

    def bootstrap(self, db):
        CRMRepository.ensure_seed_data(db, settings.admin_email, settings.admin_password, self.project_name)

    def login(self, db, payload):
        user = CRMRepository.get_user_by_email(db, payload.email)
        if user is None or not verify_password(payload.password, user.hashed_password):
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid email or password"
            )

        token = create_access_token(
            subject=user.email,
            secret_key=settings.secret_key,
            expires_minutes=settings.access_token_expire_minutes,
            extra_claims={
                "role": user.role,
                "full_name": user.full_name
            }
        )
        return {
            "access_token": token,
            "token_type": "bearer",
            "user": user
        }

    def list_customers(self, db):
        return CRMRepository.list_customers(db)

    def get_customer(self, db, customer_id: int):
        customer = CRMRepository.get_customer(db, customer_id)
        if customer is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Customer not found")
        return customer

    def create_customer(self, db, payload):
        return CRMRepository.create_customer(db, payload.model_dump())

    def update_customer(self, db, customer_id: int, payload):
        customer = self.get_customer(db, customer_id)
        return CRMRepository.update_customer(db, customer, payload.model_dump(exclude_unset=True))

    def delete_customer(self, db, customer_id: int):
        customer = self.get_customer(db, customer_id)
        CRMRepository.delete_customer(db, customer)
        return {"deleted": True, "customer_id": customer_id}

    def summary(self, db):
        return CRMRepository.dashboard_summary(db, self.project_name, self.modules)
`), { type: "source", language: "python" }),
            makeFile("backend/app/dependencies.py", block(`
from fastapi import Depends, Header, HTTPException, status
from sqlalchemy.orm import Session

from .config import settings
from .database import get_db
from .repositories.crm_repository import CRMRepository
from .security import decode_access_token


def get_current_user(authorization: str | None = Header(default=None), db: Session = Depends(get_db)):
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing bearer token"
        )

    token = authorization.removeprefix("Bearer ").strip()
    payload = decode_access_token(token, settings.secret_key)
    user = CRMRepository.get_user_by_email(db, payload.get("sub", ""))
    if user is None or not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="User not found or inactive"
        )
    return user
`), { type: "source", language: "python" }),
            makeFile("backend/app/routers/__init__.py", block(`
from .auth import router as auth_router
from .crm import router as crm_router
from .customers import router as customers_router
from .health import router as health_router
`), { type: "source", language: "python" }),
            makeFile("backend/app/routers/health.py", block(`
from fastapi import APIRouter

from ..config import settings

router = APIRouter(tags=["health"])


@router.get("/health")
def health():
    return {
        "status": "ok",
        "project": settings.app_name,
        "environment": settings.app_env
    }
`), { type: "source", language: "python" }),
            makeFile("backend/app/routers/auth.py", block(`
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from ..dependencies import get_current_user
from ..database import get_db
from ..schemas import LoginRequest, LoginResponse, UserRead
from ..services.crm_service import CRMService

router = APIRouter(prefix="/auth", tags=["auth"])
service = CRMService()


@router.post("/login", response_model=LoginResponse)
def login(payload: LoginRequest, db: Session = Depends(get_db)):
    return service.login(db, payload)


@router.get("/me", response_model=UserRead)
def me(current_user=Depends(get_current_user)):
    return current_user
`), { type: "source", language: "python" }),
            makeFile("backend/app/routers/customers.py", block(`
from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session

from ..dependencies import get_current_user
from ..database import get_db
from ..schemas import CustomerCreate, CustomerRead, CustomerUpdate
from ..services.crm_service import CRMService

router = APIRouter(prefix="/customers", tags=["customers"])
service = CRMService()


@router.get("", response_model=list[CustomerRead])
def list_customers(db: Session = Depends(get_db), current_user=Depends(get_current_user)):
    return service.list_customers(db)


@router.get("/{customer_id}", response_model=CustomerRead)
def get_customer(customer_id: int, db: Session = Depends(get_db), current_user=Depends(get_current_user)):
    return service.get_customer(db, customer_id)


@router.post("", response_model=CustomerRead, status_code=status.HTTP_201_CREATED)
def create_customer(payload: CustomerCreate, db: Session = Depends(get_db), current_user=Depends(get_current_user)):
    return service.create_customer(db, payload)


@router.put("/{customer_id}", response_model=CustomerRead)
def update_customer(customer_id: int, payload: CustomerUpdate, db: Session = Depends(get_db), current_user=Depends(get_current_user)):
    return service.update_customer(db, customer_id, payload)


@router.delete("/{customer_id}")
def delete_customer(customer_id: int, db: Session = Depends(get_db), current_user=Depends(get_current_user)):
    return service.delete_customer(db, customer_id)
`), { type: "source", language: "python" }),
            makeFile("backend/app/routers/crm.py", block(`
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from ..dependencies import get_current_user
from ..database import get_db
from ..schemas import DashboardSummary
from ..services.crm_service import CRMService

router = APIRouter(prefix="/crm", tags=["crm"])
service = CRMService()


@router.get("/summary", response_model=DashboardSummary)
def summary(db: Session = Depends(get_db), current_user=Depends(get_current_user)):
    return service.summary(db)


@router.get("/modules")
def modules():
    return {"modules": service.modules}


@router.get("/apis")
def apis():
    return {"apis": service.apis}
`), { type: "source", language: "python" }),
            makeFile("backend/app/main.py", block(`
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .config import settings
from .database import init_db
from .routers import auth_router, crm_router, customers_router, health_router
from .services.crm_service import CRMService


def create_app() -> FastAPI:
    app = FastAPI(title=settings.app_name, version="1.0.0")

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins or ["*"],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"]
    )

    @app.on_event("startup")
    def bootstrap_database():
        init_db()
        from .database import session_scope

        service = CRMService()
        with session_scope() as db:
            service.bootstrap(db)

    app.include_router(health_router)
    app.include_router(auth_router)
    app.include_router(customers_router)
    app.include_router(crm_router)

    @app.get("/")
    def root():
        return {
            "project": settings.app_name,
            "status": "ready"
        }

    return app


app = create_app()
`), { type: "source", language: "python" })
        ];
    }

    buildFrontendTemplate({ projectName, modules }) {
        const moduleList = modules.length ? modules : ["Authentication", "Dashboard", "Customers"];

        return [
            makeFile("frontend/package.json", JSON.stringify({
                name: projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
                private: true,
                type: "module",
                scripts: {
                    build: "node scripts/build.mjs",
                    check: "node scripts/check.mjs"
                }
            }, null, 2) + "\n", { type: "configuration", language: "json" }),
            makeFile("frontend/vite.config.js", block(`
export default {
  root: ".",
  build: {
    outDir: "dist",
    emptyOutDir: true
  }
};
`), { type: "configuration", language: "javascript" }),
            makeFile("frontend/index.html", block(`
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`), { type: "markup", language: "html" }),
            makeFile("frontend/README.md", block(`
# ${projectName} Frontend

## Stack

- Vite-compatible structure
- React-style source layout
- Self-contained build script

## Build

\`\`\`bash
npm install
npm run build
\`\`\`
`), { type: "documentation", language: "markdown" }),
            makeFile("frontend/public/.gitkeep", "", { type: "placeholder", language: "text" }),
            makeFile("frontend/scripts/build.mjs", block(`
import fs from "fs";
import path from "path";

const root = process.cwd();
const dist = path.join(root, "dist");
const src = path.join(root, "src");

fs.mkdirSync(dist, { recursive: true });

const html = \`<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
  <body>
    <div id="root">
      <h1>${projectName}</h1>
      <p>Generated build artifact.</p>
      <ul>
        ${moduleList.map(moduleName => `<li>${moduleName}</li>`).join("\\n        ")}
      </ul>
    </div>
  </body>
</html>\`;

fs.writeFileSync(path.join(dist, "index.html"), html);
fs.writeFileSync(path.join(dist, "build-summary.json"), JSON.stringify({
  project: "${projectName}",
  sourceDir: src,
  generatedAt: new Date().toISOString()
}, null, 2));

console.log("Frontend build completed.");
`), { type: "source", language: "javascript" }),
            makeFile("frontend/scripts/check.mjs", block(`
import fs from "fs";
import path from "path";

const required = [
  "package.json",
  "vite.config.js",
  "index.html",
  "src/main.jsx",
  "src/App.jsx"
];

for (const file of required) {
  if (!fs.existsSync(path.join(process.cwd(), file))) {
    throw new Error(\`Missing required file: \${file}\`);
  }
}

console.log("Frontend structure check passed.");
`), { type: "source", language: "javascript" }),
            makeFile("frontend/src/main.jsx", block(`
import App from "./App.jsx";
import "./styles.css";

const root = document.getElementById("root");

if (root) {
  root.innerHTML = App();
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/App.jsx", block(`
import { renderLayout } from "./layouts/MainLayout.jsx";

export default function App() {
  return renderLayout({
    title: "${projectName}",
    modules: ${JSON.stringify(moduleList, null, 2)}
  });
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/layouts/MainLayout.jsx", block(`
export function renderLayout({ title, modules = [] }) {
  return \`
    <main class="app-shell">
      <section class="hero">
        <p class="eyebrow">ANNEXE AI</p>
        <h1>\${title}</h1>
        <p>Generated enterprise CRM foundation.</p>
      </section>
      <section class="modules">
        \${modules.map(module => \`<article class="card"><h2>\${module}</h2></article>\`).join("")}
      </section>
    </main>
  \`;
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/pages/Login.jsx", block(`
export default function Login() {
  return \`
    <main class="page">
      <h1>${projectName} Login</h1>
      <p>Secure access for sales and operations teams.</p>
    </main>
  \`;
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/pages/Dashboard.jsx", block(`
export default function Dashboard() {
  return \`
    <main class="page">
      <h1>${projectName} Dashboard</h1>
      <p>Customer, lead, and pipeline overview.</p>
    </main>
  \`;
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/pages/Customers.jsx", block(`
export default function Customers() {
  return \`
    <main class="page">
      <h1>Customers</h1>
      <p>Enterprise CRM customer management workspace.</p>
    </main>
  \`;
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/components/index.js", "export {};\n", { type: "source", language: "javascript" }),
            makeFile("frontend/src/layouts/index.js", "export {};\n", { type: "source", language: "javascript" }),
            makeFile("frontend/src/hooks/index.js", "export {};\n", { type: "source", language: "javascript" }),
            makeFile("frontend/src/services/index.js", "export {};\n", { type: "source", language: "javascript" }),
            makeFile("frontend/src/contexts/index.js", "export {};\n", { type: "source", language: "javascript" }),
            makeFile("frontend/src/assets/.gitkeep", "", { type: "placeholder", language: "text" }),
            makeFile("frontend/src/styles.css", block(`
:root {
  color-scheme: light;
  font-family: Inter, system-ui, sans-serif;
}

body {
  margin: 0;
  background: linear-gradient(180deg, #f8fbff, #eef3f8);
  color: #102030;
}

.app-shell,
.page {
  padding: 2rem;
}

.modules {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 1rem;
}

.card {
  padding: 1rem;
  border-radius: 16px;
  background: white;
  box-shadow: 0 10px 30px rgba(16, 32, 48, 0.08);
}
`), { type: "source", language: "css" })
        ];
    }

    buildFrontendTemplateV2({ projectName, modules }) {
        const moduleList = modules.length ? modules : ["Authentication", "Dashboard", "Customers", "Reporting"];
        const defaultAdminEmail = "admin@annexe.ai";
        const defaultAdminPassword = "Admin123!";

        return [
            makeFile("frontend/package.json", JSON.stringify({
                name: projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
                private: true,
                type: "module",
                scripts: {
                    dev: "vite",
                    build: "vite build",
                    preview: "vite preview",
                    check: "node scripts/check.mjs"
                },
                dependencies: {
                    react: "^18.3.1",
                    "react-dom": "^18.3.1",
                    "react-router-dom": "^6.26.2"
                },
                devDependencies: {
                    "@vitejs/plugin-react": "^4.3.1",
                    vite: "^5.4.2"
                }
            }, null, 2) + "\n", { type: "configuration", language: "json" }),
            makeFile("frontend/vite.config.js", block(`
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: {
    host: "0.0.0.0",
    port: 5173
  }
});
`), { type: "configuration", language: "javascript" }),
            makeFile("frontend/index.html", block(`
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#0f172a" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`), { type: "markup", language: "html" }),
            makeFile("frontend/README.md", block(`
# ${projectName} Frontend

## Features

- React Router powered navigation
- Login screen backed by the API client
- Dashboard, customer list, and customer detail views

## Default Login

- Email: ${defaultAdminEmail}
- Password: ${defaultAdminPassword}

## Run

\`\`\`bash
npm install
npm run build
\`\`\`
`), { type: "documentation", language: "markdown" }),
            makeFile("frontend/public/.gitkeep", "", { type: "placeholder", language: "text" }),
            makeFile("frontend/scripts/check.mjs", block(`
import fs from "fs";
import path from "path";

const required = [
  "package.json",
  "vite.config.js",
  "index.html",
  "src/main.jsx",
  "src/App.jsx",
  "src/pages/Login.jsx",
  "src/pages/Dashboard.jsx",
  "src/pages/Customers.jsx",
  "src/pages/CustomerDetails.jsx",
  "src/services/api.js",
  "src/contexts/AuthContext.jsx"
];

for (const file of required) {
  if (!fs.existsSync(path.join(process.cwd(), file))) {
    throw new Error(\`Missing required file: \${file}\`);
  }
}

console.log("Frontend structure check passed.");
`), { type: "source", language: "javascript" }),
            makeFile("frontend/src/main.jsx", block(`
import { StrictMode } from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";

import App from "./App.jsx";
import { AuthProvider } from "./contexts/AuthContext.jsx";
import "./styles.css";

ReactDOM.createRoot(document.getElementById("root")).render(
  <StrictMode>
    <BrowserRouter>
      <AuthProvider>
        <App />
      </AuthProvider>
    </BrowserRouter>
  </StrictMode>
);
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/App.jsx", block(`
import { Navigate, Route, Routes } from "react-router-dom";

import { RequireAuth } from "./contexts/AuthContext.jsx";
import { MainLayout } from "./layouts/MainLayout.jsx";
import CustomerDetails from "./pages/CustomerDetails.jsx";
import Customers from "./pages/Customers.jsx";
import Dashboard from "./pages/Dashboard.jsx";
import Login from "./pages/Login.jsx";

export default function App() {
  return (
    <Routes>
      <Route path="/login" element={<Login />} />
      <Route
        element={
          <RequireAuth>
            <MainLayout />
          </RequireAuth>
        }
      >
        <Route index element={<Dashboard />} />
        <Route path="customers" element={<Customers />} />
        <Route path="customers/:customerId" element={<CustomerDetails />} />
      </Route>
      <Route path="*" element={<Navigate to="/" replace />} />
    </Routes>
  );
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/layouts/MainLayout.jsx", block(`
import { NavLink, Outlet, useNavigate } from "react-router-dom";

import { useAuth } from "../contexts/AuthContext.jsx";

export function MainLayout() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    navigate("/login", { replace: true });
  };

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand">
          <span className="brand-mark">A</span>
          <div>
            <strong>${projectName}</strong>
            <p>Enterprise CRM</p>
          </div>
        </div>

        <nav className="nav">
          <NavLink to="/" end>
            Dashboard
          </NavLink>
          <NavLink to="/customers">Customers</NavLink>
        </nav>

        <div className="sidebar-footer">
          <p>{user?.full_name}</p>
          <button type="button" className="button button-secondary" onClick={handleLogout}>
            Sign out
          </button>
        </div>
      </aside>

      <main className="workspace">
        <header className="workspace-header">
          <div>
            <p className="eyebrow">ANNEXE AI</p>
            <h1>${projectName}</h1>
          </div>
          <div className="status-pill">Authenticated</div>
        </header>

        <Outlet />
      </main>
    </div>
  );
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/contexts/AuthContext.jsx", block(`
import { createContext, useContext, useEffect, useState } from "react";
import { Navigate, useLocation } from "react-router-dom";

import { apiClient, clearStoredToken, getStoredToken, setStoredToken } from "../services/api.js";

const AuthContext = createContext(null);

export function AuthProvider({ children }) {
  const [token, setToken] = useState(() => getStoredToken());
  const [user, setUser] = useState(null);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    let active = true;

    async function hydrate() {
      if (!token) {
        setReady(true);
        return;
      }

      try {
        const me = await apiClient.me(token);
        if (active) {
          setUser(me);
        }
      } catch {
        clearStoredToken();
        if (active) {
          setToken(null);
          setUser(null);
        }
      } finally {
        if (active) {
          setReady(true);
        }
      }
    }

    hydrate();

    return () => {
      active = false;
    };
  }, [token]);

  async function login(email, password) {
    const response = await apiClient.login({ email, password });
    setStoredToken(response.access_token);
    setToken(response.access_token);
    setUser(response.user);
    return response.user;
  }

  function logout() {
    clearStoredToken();
    setToken(null);
    setUser(null);
  }

  return (
    <AuthContext.Provider value={{ token, user, ready, login, logout }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error("useAuth must be used within an AuthProvider");
  }
  return context;
}

export function RequireAuth({ children }) {
  const { token, ready } = useAuth();
  const location = useLocation();

  if (!ready) {
    return <div className="screen screen-loading">Loading workspace...</div>;
  }

  if (!token) {
    return <Navigate to="/login" replace state={{ from: location.pathname }} />;
  }

  return children;
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/services/api.js", block(`
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? "http://127.0.0.1:8000";
const TOKEN_KEY = "annexe.crm.token";

export function getStoredToken() {
  return window.localStorage.getItem(TOKEN_KEY);
}

export function setStoredToken(token) {
  window.localStorage.setItem(TOKEN_KEY, token);
}

export function clearStoredToken() {
  window.localStorage.removeItem(TOKEN_KEY);
}

async function request(path, options = {}) {
  const {
    method = "GET",
    body,
    token = undefined,
    headers = {}
  } = options;

  const authToken = token === undefined ? getStoredToken() : token;
  const response = await fetch(\`\${API_BASE_URL}\${path}\`, {
    method,
    headers: {
      "Content-Type": "application/json",
      ...(authToken ? { Authorization: \`Bearer \${authToken}\` } : {}),
      ...headers
    },
    body: body === undefined ? undefined : JSON.stringify(body)
  });

  const payload = await response.json().catch(() => null);
  if (!response.ok) {
    throw new Error(payload?.detail || payload?.message || "Request failed");
  }

  return payload;
}

export const apiClient = {
  login(credentials) {
    return request("/auth/login", {
      method: "POST",
      body: credentials,
      token: null
    });
  },
  me(token) {
    return request("/auth/me", { token });
  },
  summary(token) {
    return request("/crm/summary", { token });
  },
  listCustomers(token) {
    return request("/customers", { token });
  },
  getCustomer(customerId, token) {
    return request(\`/customers/\${customerId}\`, { token });
  },
  createCustomer(payload, token) {
    return request("/customers", {
      method: "POST",
      body: payload,
      token
    });
  },
  updateCustomer(customerId, payload, token) {
    return request(\`/customers/\${customerId}\`, {
      method: "PUT",
      body: payload,
      token
    });
  },
  deleteCustomer(customerId, token) {
    return request(\`/customers/\${customerId}\`, {
      method: "DELETE",
      token
    });
  }
};
`), { type: "source", language: "javascript" }),
            makeFile("frontend/src/services/index.js", block(`
export { apiClient, clearStoredToken, getStoredToken, setStoredToken } from "./api.js";
`), { type: "source", language: "javascript" }),
            makeFile("frontend/src/layouts/index.js", block(`
export { MainLayout } from "./MainLayout.jsx";
`), { type: "source", language: "javascript" }),
            makeFile("frontend/src/contexts/index.js", block(`
export { AuthProvider, RequireAuth, useAuth } from "./AuthContext.jsx";
`), { type: "source", language: "javascript" }),
            makeFile("frontend/src/components/StatCard.jsx", block(`
export function StatCard({ label, value, note }) {
  return (
    <article className="stat-card">
      <p>{label}</p>
      <strong>{value}</strong>
      {note ? <span>{note}</span> : null}
    </article>
  );
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/components/index.js", block(`
export { StatCard } from "./StatCard.jsx";
`), { type: "source", language: "javascript" }),
            makeFile("frontend/src/pages/Login.jsx", block(`
import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";

import { useAuth } from "../contexts/AuthContext.jsx";

const DEFAULT_EMAIL = "${defaultAdminEmail}";
const DEFAULT_PASSWORD = "${defaultAdminPassword}";

export default function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [email, setEmail] = useState(DEFAULT_EMAIL);
  const [password, setPassword] = useState(DEFAULT_PASSWORD);
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  async function handleSubmit(event) {
    event.preventDefault();
    setSubmitting(true);
    setError("");

    try {
      await login(email, password);
      const destination = location.state?.from || "/";
      navigate(destination, { replace: true });
    } catch (err) {
      setError(err.message || "Unable to sign in");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <main className="auth-shell">
      <section className="auth-card">
        <p className="eyebrow">Enterprise CRM</p>
        <h1>Sign in to your workspace</h1>
        <p className="auth-copy">
          Access the seeded dashboard, protected customer records, and the full CRM shell.
        </p>

        <form className="auth-form" onSubmit={handleSubmit}>
          <label>
            Email
            <input value={email} onChange={(event) => setEmail(event.target.value)} type="email" />
          </label>
          <label>
            Password
            <input
              value={password}
              onChange={(event) => setPassword(event.target.value)}
              type="password"
            />
          </label>

          {error ? <div className="form-error">{error}</div> : null}

          <button type="submit" className="button button-primary" disabled={submitting}>
            {submitting ? "Signing in..." : "Sign in"}
          </button>
        </form>

        <p className="helper-text">
          Default credentials: <strong>{DEFAULT_EMAIL}</strong> / <strong>{DEFAULT_PASSWORD}</strong>
        </p>
      </section>
    </main>
  );
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/pages/Dashboard.jsx", block(`
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";

import { StatCard } from "../components/StatCard.jsx";
import { useAuth } from "../contexts/AuthContext.jsx";
import { apiClient } from "../services/api.js";

export default function Dashboard() {
  const { user } = useAuth();
  const [summary, setSummary] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    let active = true;

    async function loadSummary() {
      try {
        const data = await apiClient.summary();
        if (active) {
          setSummary(data);
        }
      } catch (err) {
        if (active) {
          setError(err.message || "Unable to load dashboard");
        }
      }
    }

    loadSummary();

    return () => {
      active = false;
    };
  }, []);

  return (
    <section className="content-stack">
      <div className="hero-card">
        <div>
          <p className="eyebrow">Workspace overview</p>
          <h2>Welcome back, {user?.full_name ?? "Admin"}.</h2>
          <p>Monitor customer engagement, active accounts, and recent CRM activity.</p>
        </div>
        <Link className="button button-primary" to="/customers">
          Open customers
        </Link>
      </div>

      {error ? <div className="form-error">{error}</div> : null}

      <div className="stats-grid">
        <StatCard label="Customers" value={summary?.customer_count ?? "..."} note="Total accounts" />
        <StatCard
          label="Active"
          value={summary?.active_customer_count ?? "..."}
          note="Currently active accounts"
        />
        <StatCard label="Users" value={summary?.user_count ?? "..."} note="Seeded users" />
      </div>

      <section className="panel">
        <div className="panel-header">
          <h3>Modules</h3>
          <span>{summary?.modules?.length ?? 0} enabled modules</span>
        </div>
        <div className="chip-row">
          {(summary?.modules ?? []).map((moduleName) => (
            <span className="chip" key={moduleName}>
              {moduleName}
            </span>
          ))}
        </div>
      </section>

      <section className="panel">
        <div className="panel-header">
          <h3>Recent customers</h3>
          <span>{summary?.recent_customers?.length ?? 0} records</span>
        </div>
        <div className="recent-list">
          {(summary?.recent_customers ?? []).map((customer) => (
            <Link className="recent-item" to={"/customers/" + customer.id} key={customer.id}>
              <strong>{customer.name}</strong>
              <span>
                {customer.company ?? "Unknown company"} · {customer.status}
              </span>
            </Link>
          ))}
        </div>
      </section>
    </section>
  );
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/pages/Customers.jsx", block(`
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";

import { apiClient } from "../services/api.js";

export default function Customers() {
  const [customers, setCustomers] = useState([]);
  const [query, setQuery] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    let active = true;

    async function loadCustomers() {
      try {
        const data = await apiClient.listCustomers();
        if (active) {
          setCustomers(data);
        }
      } catch (err) {
        if (active) {
          setError(err.message || "Unable to load customers");
        }
      }
    }

    loadCustomers();

    return () => {
      active = false;
    };
  }, []);

  const filteredCustomers = useMemo(() => {
    const term = query.trim().toLowerCase();
    if (!term) {
      return customers;
    }

    return customers.filter((customer) => {
      return [customer.name, customer.company, customer.email, customer.owner]
        .filter(Boolean)
        .some((value) => value.toLowerCase().includes(term));
    });
  }, [customers, query]);

  return (
    <section className="content-stack">
      <div className="panel">
        <div className="panel-header">
          <h2>Customer list</h2>
          <span>{filteredCustomers.length} visible customers</span>
        </div>
        <input
          className="search-input"
          placeholder="Search by name, company, owner, or email"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
        />
      </div>

      {error ? <div className="form-error">{error}</div> : null}

      <div className="customer-grid">
        {filteredCustomers.map((customer) => (
          <article className="customer-card" key={customer.id}>
            <div className="customer-card-header">
              <div>
                <h3>{customer.name}</h3>
                <p>{customer.company ?? "Independent account"}</p>
              </div>
              <span className={"status-pill status-" + customer.status}>{customer.status}</span>
            </div>
            <dl>
              <div>
                <dt>Email</dt>
                <dd>{customer.email ?? "Not provided"}</dd>
              </div>
              <div>
                <dt>Owner</dt>
                <dd>{customer.owner ?? "Unassigned"}</dd>
              </div>
            </dl>
            <Link className="button button-secondary" to={"/customers/" + customer.id}>
              View details
            </Link>
          </article>
        ))}
      </div>
    </section>
  );
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/pages/CustomerDetails.jsx", block(`
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";

import { apiClient } from "../services/api.js";

export default function CustomerDetails() {
  const { customerId } = useParams();
  const [customer, setCustomer] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    let active = true;

    async function loadCustomer() {
      try {
        const data = await apiClient.getCustomer(customerId);
        if (active) {
          setCustomer(data);
        }
      } catch (err) {
        if (active) {
          setError(err.message || "Unable to load customer");
        }
      }
    }

    loadCustomer();

    return () => {
      active = false;
    };
  }, [customerId]);

  if (error) {
    return (
      <section className="content-stack">
        <div className="panel">
          <p className="form-error">{error}</p>
          <Link className="button button-secondary" to="/customers">
            Back to customers
          </Link>
        </div>
      </section>
    );
  }

  if (!customer) {
    return (
      <section className="content-stack">
        <div className="panel">Loading customer profile...</div>
      </section>
    );
  }

  return (
    <section className="content-stack">
      <div className="hero-card">
        <div>
          <p className="eyebrow">Customer profile</p>
          <h2>{customer.name}</h2>
          <p>{customer.company ?? "No company provided"}</p>
        </div>
        <Link className="button button-secondary" to="/customers">
          Back to customers
        </Link>
      </div>

      <section className="panel">
        <div className="panel-header">
          <h3>Details</h3>
          <span className={"status-pill status-" + customer.status}>{customer.status}</span>
        </div>
        <dl className="detail-grid">
          <div>
            <dt>Email</dt>
            <dd>{customer.email ?? "Not provided"}</dd>
          </div>
          <div>
            <dt>Phone</dt>
            <dd>{customer.phone ?? "Not provided"}</dd>
          </div>
          <div>
            <dt>Owner</dt>
            <dd>{customer.owner ?? "Unassigned"}</dd>
          </div>
          <div>
            <dt>Created</dt>
            <dd>{new Date(customer.created_at).toLocaleString()}</dd>
          </div>
        </dl>
      </section>

      <section className="panel">
        <h3>Notes</h3>
        <p>{customer.notes ?? "No notes available for this customer."}</p>
      </section>
    </section>
  );
}
`), { type: "source", language: "jsx" }),
            makeFile("frontend/src/hooks/index.js", block(`
export {};
`), { type: "source", language: "javascript" }),
            makeFile("frontend/src/assets/.gitkeep", "", { type: "placeholder", language: "text" }),
            makeFile("frontend/src/styles.css", block(`
:root {
  color-scheme: dark;
  font-family: Inter, "Segoe UI", system-ui, sans-serif;
  background: #08111f;
  color: #e6eefc;
  line-height: 1.5;
  font-weight: 400;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-width: 320px;
  min-height: 100vh;
  background:
    radial-gradient(circle at top left, rgba(68, 114, 196, 0.28), transparent 35%),
    radial-gradient(circle at top right, rgba(20, 184, 166, 0.18), transparent 32%),
    linear-gradient(180deg, #08111f 0%, #0c1729 100%);
}

a {
  color: inherit;
  text-decoration: none;
}

button,
input {
  font: inherit;
}

#root {
  min-height: 100vh;
}

.screen,
.app-shell,
.auth-shell {
  min-height: 100vh;
}

.screen-loading {
  display: grid;
  place-items: center;
  color: #94a3b8;
}

.auth-shell {
  display: grid;
  place-items: center;
  padding: 2rem;
}

.auth-card,
.panel,
.hero-card,
.customer-card,
.stat-card {
  background: rgba(10, 18, 32, 0.82);
  border: 1px solid rgba(148, 163, 184, 0.18);
  box-shadow: 0 24px 80px rgba(2, 6, 23, 0.42);
  backdrop-filter: blur(18px);
}

.auth-card {
  width: min(100%, 460px);
  padding: 2rem;
  border-radius: 24px;
}

.auth-form,
.content-stack {
  display: grid;
  gap: 1rem;
}

.auth-form label {
  display: grid;
  gap: 0.4rem;
  color: #cbd5e1;
}

.auth-form input,
.search-input {
  width: 100%;
  border-radius: 14px;
  border: 1px solid rgba(148, 163, 184, 0.22);
  background: rgba(15, 23, 42, 0.9);
  color: #e2e8f0;
  padding: 0.85rem 1rem;
}

.auth-copy,
.helper-text,
.panel span,
.customer-card p,
.recent-item span,
.stat-card span,
.stat-card p {
  color: #94a3b8;
}

.form-error {
  padding: 0.85rem 1rem;
  border-radius: 14px;
  background: rgba(127, 29, 29, 0.22);
  color: #fecaca;
}

.button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  border: 0;
  border-radius: 14px;
  padding: 0.85rem 1.1rem;
  cursor: pointer;
  transition: transform 0.18s ease, background 0.18s ease, color 0.18s ease;
}

.button:hover {
  transform: translateY(-1px);
}

.button-primary {
  background: linear-gradient(135deg, #2563eb, #06b6d4);
  color: #f8fbff;
}

.button-secondary {
  background: rgba(30, 41, 59, 0.9);
  color: #e2e8f0;
}

.app-shell {
  display: grid;
  grid-template-columns: 280px minmax(0, 1fr);
}

.sidebar {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  padding: 1.5rem;
  border-right: 1px solid rgba(148, 163, 184, 0.14);
  background: rgba(2, 6, 23, 0.58);
}

.brand {
  display: flex;
  align-items: center;
  gap: 0.9rem;
}

.brand-mark {
  display: grid;
  place-items: center;
  width: 44px;
  height: 44px;
  border-radius: 14px;
  background: linear-gradient(135deg, #2563eb, #0ea5e9);
  font-weight: 700;
}

.brand p,
.sidebar-footer p {
  margin: 0.2rem 0 0;
  color: #94a3b8;
}

.nav {
  display: grid;
  gap: 0.45rem;
  margin: 2rem 0;
}

.nav a {
  padding: 0.85rem 1rem;
  border-radius: 14px;
  color: #cbd5e1;
  background: transparent;
}

.nav a.active {
  background: rgba(37, 99, 235, 0.2);
  color: #eff6ff;
}

.workspace {
  padding: 1.5rem;
}

.workspace-header,
.panel-header,
.hero-card,
.customer-card-header,
.detail-grid {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
}

.workspace-header {
  align-items: center;
  margin-bottom: 1.5rem;
}

.eyebrow {
  margin: 0 0 0.35rem;
  text-transform: uppercase;
  letter-spacing: 0.18em;
  font-size: 0.74rem;
  color: #7dd3fc;
}

.hero-card,
.panel,
.customer-card {
  padding: 1.25rem;
  border-radius: 22px;
}

.stats-grid,
.customer-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 1rem;
}

.stat-card strong {
  display: block;
  margin: 0.35rem 0;
  font-size: 2rem;
  color: #f8fafc;
}

.chip-row,
.recent-list {
  display: flex;
  flex-wrap: wrap;
  gap: 0.65rem;
}

.chip,
.status-pill {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  border-radius: 999px;
  padding: 0.45rem 0.8rem;
  background: rgba(30, 41, 59, 0.8);
  color: #cbd5e1;
  font-size: 0.9rem;
}

.status-active {
  background: rgba(16, 185, 129, 0.18);
  color: #a7f3d0;
}

.status-prospect {
  background: rgba(250, 204, 21, 0.18);
  color: #fde68a;
}

.recent-item {
  display: grid;
  gap: 0.2rem;
  padding: 1rem;
  border-radius: 16px;
  background: rgba(15, 23, 42, 0.88);
}

.customer-card {
  display: grid;
  gap: 1rem;
}

.customer-card dl,
.detail-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 0.9rem;
  margin: 0;
}

.customer-card dt,
.detail-grid dt {
  font-size: 0.82rem;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: #94a3b8;
}

.customer-card dd,
.detail-grid dd {
  margin: 0.2rem 0 0;
  color: #e2e8f0;
}

@media (max-width: 900px) {
  .app-shell {
    grid-template-columns: 1fr;
  }

  .sidebar {
    border-right: 0;
    border-bottom: 1px solid rgba(148, 163, 184, 0.14);
  }
}
`), { type: "source", language: "css" })
        ];
    }

    composeArtifacts(manifest) {
        const blueprint = manifest.blueprint ?? {};
        const projectName =
            blueprint.metadata?.projectName ??
            manifest.project?.name ??
            manifest.projectId ??
            "Enterprise CRM";

        const modules = blueprint.businessModules?.modules ?? blueprint.modules ?? [];
        const entities = blueprint.businessModules?.entities ?? blueprint.entities ?? [];
        const services = blueprint.businessModules?.services ?? blueprint.services ?? [];
        const apis = blueprint.businessModules?.apis ?? blueprint.apis ?? [];

        const map = new Map();
        const add = file => {
            if (!file?.path) return;
            map.set(normalizePath(file.path), {
                ...file,
                path: normalizePath(file.path)
            });
        };

        for (const file of this.buildRootFiles({ projectName, blueprint })) add(file);
        for (const file of this.buildBackendTemplate({ projectName, modules, entities, services, apis })) add(file);
        for (const file of this.buildFrontendTemplateV2({ projectName, modules })) add(file);
        for (const file of blueprint.files ?? []) add(file);
        for (const file of manifest.artifacts ?? []) add(file);

        return Array.from(map.values());
    }

    write(manifest) {
        if (!manifest)
            throw new Error("BuildManifest is required.");

        const report = new WriteReport({
            manifestId: manifest.manifestId,
            projectId: manifest.projectId
        });

        const projectRoot = path.join(this.workspaceRoot, manifest.projectId);

        if (!fs.existsSync(projectRoot)) {
            fs.mkdirSync(projectRoot, { recursive: true });
            report.addDirectory(projectRoot);
        }

        const artifacts = this.composeArtifacts(manifest);

        for (const file of artifacts) {
            const outputPath = path.join(projectRoot, file.path);
            const directory = path.dirname(outputPath);

            if (!fs.existsSync(directory)) {
                fs.mkdirSync(directory, { recursive: true });
                report.addDirectory(directory);
            }

            if (fs.existsSync(outputPath) && file.overwrite === false) {
                report.addSkipped(outputPath);
                continue;
            }

            if (fs.existsSync(outputPath) && file.overwrite === true) {
                report.addOverwritten(outputPath);
            }

            try {
                fs.writeFileSync(outputPath, file.content ?? "", {
                    encoding: file.encoding ?? "utf8"
                });
                report.addWritten(outputPath);
            }
            catch (error) {
                report.addError(outputPath, error);
            }
        }

        report.complete();
        return report;
    }

}
